import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Learn sidebar - contains tutorials and getting started content
  learnSidebar: [{type: 'autogenerated', dirName: 'learn'}],
  
  // Reference sidebar - contains API docs and technical reference
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
  
  // Examples sidebar - contains code examples and practical guides
  examplesSidebar: [{type: 'autogenerated', dirName: 'examples'}],
};

export default sidebars;
